import img1 from '~/assets/images/T-shirt.png';
import img2 from '~/assets/images/shirt.png';
import img3 from '~/assets/images/trousers.png';

export const Data = [
    {
        id: 1,
        name: '세터 로고 자수 보야지 반팔 티셔츠',
        seller: '무신사 (Musinsa)',
        price: 79000,
        categoryId: '시원한',
        imgSrc: img1,
        gender: '남',
    },
    {
        id: 2,
        name: '그라데이션 오피서 하프 셔츠',
        seller: '무신사 (Musinsa)',
        price: 103000,
        categoryId: '독특한',
        imgSrc: img2,
        gender: '남',
    },
    {
        id: 3,
        name: 'XP138 파스텔 데님 카고 팬츠',
        seller: '에이블리 ',
        price: 9000,
        categoryId: '화려한',
        imgSrc: img3,
        gender: '남',
    },
    {
        id: 4,
        name: '세터 로고 자수 보야지 반팔 티셔츠',
        seller: '무신사 (Musinsa)',
        price: 79000,
        categoryId: '시원한',
        imgSrc: img1,
        gender: '남',
    },
    {
        id: 5,
        name: '그라데이션 오피서 하프 셔츠',
        seller: '무신사 (Musinsa)',
        price: 103000,
        categoryId: '시원한',
        imgSrc: img2,
        gender: '남',
    },
    {
        id: 6,
        name: 'XP138 파스텔 데님 카고 팬츠',
        seller: '에이블리 ',
        price: 9000,
        categoryId: '화려한',
        imgSrc: img3,
        gender: '남',
    },
    {
        id: 7,
        name: '세터 로고 자수 보야지 반팔 티셔츠',
        seller: '무신사 (Musinsa)',
        price: 79000,
        categoryId: '독특한',
        imgSrc: img1,
        gender: '남',
    },
    {
        id: 8,
        name: '그라데이션 오피서 하프 셔츠',
        seller: '무신사 (Musinsa)',
        price: 103000,
        categoryId: '시원한',
        imgSrc: img2,
        gender: '남',
    },
    {
        id: 9,
        name: 'XP138 파스텔 데님 카고 팬츠',
        seller: '에이블리 ',
        price: 9000,
        categoryId: '화려한',
        imgSrc: img3,
        gender: '남',
    },
    {
        id: 10,
        name: '세터 로고 자수 보야지 반팔 티셔츠',
        seller: '무신사 (Musinsa)',
        price: 79000,
        categoryId: '시원한',
        imgSrc: img1,
        gender: '남',
    },
    {
        id: 11,
        name: '그라데이션 오피서 하프 셔츠',
        seller: '무신사 (Musinsa)',
        price: 103000,
        categoryId: '독특한',
        imgSrc: img2,
        gender: '남여공용',
    },
    {
        id: 12,
        name: 'XP138 파스텔 데님 카고 팬츠',
        seller: '에이블리 ',
        price: 9000,
        categoryId: '화려한',
        imgSrc: img3,
        gender: '여',
    },
];
